-- MySQL Script generated by MySQL Workbench
-- 01/07/18 15:01:28
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema familyorganizer
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema familyorganizer
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `familyorganizer` DEFAULT CHARACTER SET utf8 ;
USE `familyorganizer` ;

-- -----------------------------------------------------
-- Table `familyorganizer`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `familyorganizer`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NULL DEFAULT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `birthday` DATE NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `username` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `familyorganizer`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `familyorganizer`.`category` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL DEFAULT NULL,
  `creator` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_category_user1_idx` (`creator` ASC),
  CONSTRAINT `fk_category_user1`
    FOREIGN KEY (`creator`)
    REFERENCES `familyorganizer`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `familyorganizer`.`image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `familyorganizer`.`image` (
  `id` INT(11) NOT NULL,
  `image` BLOB NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `familyorganizer`.`pocketmoney`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `familyorganizer`.`pocketmoney` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `amount` DECIMAL(10,0) NULL DEFAULT NULL,
  `user` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pocketmoney_user1_idx` (`user` ASC),
  CONSTRAINT `fk_pocketmoney_user1`
    FOREIGN KEY (`user`)
    REFERENCES `familyorganizer`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `familyorganizer`.`pocketmoney_month`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `familyorganizer`.`pocketmoney_month` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `amount` DECIMAL(10,0) NULL DEFAULT NULL,
  `user` INT(11) NOT NULL,
  `month` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_table1_user1_idx` (`user` ASC),
  CONSTRAINT `fk_table1_user1`
    FOREIGN KEY (`user`)
    REFERENCES `familyorganizer`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `familyorganizer`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `familyorganizer`.`products` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL DEFAULT NULL,
  `creator` INT(11) NOT NULL,
  `category` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_products_user1_idx` (`creator` ASC),
  INDEX `fk_products_category1_idx` (`category` ASC),
  CONSTRAINT `fk_products_category1`
    FOREIGN KEY (`category`)
    REFERENCES `familyorganizer`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_user1`
    FOREIGN KEY (`creator`)
    REFERENCES `familyorganizer`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `familyorganizer`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `familyorganizer`.`role` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `familyorganizer`.`unit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `familyorganizer`.`unit` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `familyorganizer`.`shoppinglist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `familyorganizer`.`shoppinglist` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `purchaser` INT(11) NULL DEFAULT NULL,
  `product` INT(11) NOT NULL,
  `price` DECIMAL(10,0) NULL DEFAULT NULL,
  `shoppingdate` DATE NULL DEFAULT NULL,
  `amount` INT(11) NULL DEFAULT NULL,
  `unit` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_shoppinglist_user1_idx` (`purchaser` ASC),
  INDEX `fk_shoppinglist_products1_idx` (`product` ASC),
  INDEX `fk_shoppinglist_unit1_idx` (`unit` ASC),
  CONSTRAINT `fk_shoppinglist_products1`
    FOREIGN KEY (`product`)
    REFERENCES `familyorganizer`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_shoppinglist_unit1`
    FOREIGN KEY (`unit`)
    REFERENCES `familyorganizer`.`unit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_shoppinglist_user1`
    FOREIGN KEY (`purchaser`)
    REFERENCES `familyorganizer`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `familyorganizer`.`task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `familyorganizer`.`task` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `description` TINYTEXT NULL DEFAULT NULL,
  `creator` INT(11) NOT NULL,
  `lastdo` DATE NULL DEFAULT NULL,
  `image` INT(11) NULL DEFAULT NULL,
  `standard` VARCHAR(1) NULL DEFAULT '1',
  `price` DOUBLE NULL DEFAULT '0',
  `active` VARCHAR(1) NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  INDEX `fk_issues_user1_idx` (`creator` ASC),
  INDEX `fk_issues_image1_idx` (`image` ASC),
  CONSTRAINT `fk_issues_image1`
    FOREIGN KEY (`image`)
    REFERENCES `familyorganizer`.`image` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_issues_user1`
    FOREIGN KEY (`creator`)
    REFERENCES `familyorganizer`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `familyorganizer`.`user_do_task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `familyorganizer`.`user_do_task` (
  `user_id` INT(11) NOT NULL,
  `task_id` INT(11) NOT NULL,
  `date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`, `task_id`),
  INDEX `fk_user_has_task_task1_idx` (`task_id` ASC),
  INDEX `fk_user_has_task_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_has_task_task1`
    FOREIGN KEY (`task_id`)
    REFERENCES `familyorganizer`.`task` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_task_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `familyorganizer`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `familyorganizer`.`user_has_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `familyorganizer`.`user_has_role` (
  `user_id` INT(11) NOT NULL,
  `role_id` INT(11) NOT NULL,
  PRIMARY KEY (`user_id`, `role_id`),
  INDEX `fk_user_has_role_role1_idx` (`role_id` ASC),
  INDEX `fk_user_has_role_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_has_role_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `familyorganizer`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_role_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `familyorganizer`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
